### ISSUE TITLE
Tabelle fc_tokens existiert nicht

### ISSUE THREAD

**Issue by Webmeteor** [flatCore/flatCore-CMS#11]
die Tabelle fc_tokens wird vom Installer nicht angelegt.

Beim erstmaligen einloggen kommt
Fatal error: Call to a member function bindValue() on boolean in /core/functions/func_userdata.php on line 209

habe dann mal errorInfo eingebaut mit folgendem Ergebnis:
Array ( [0] => HY000 [1] => 1 [2] => no such table: fc_tokens )

**Comment by patkon** [comment]
Habe den Fehler behoben: https://github.com/flatCore/flatCore-CMS/commit/4e6e2370201890a5b6ff274d8c2b3d70f4061d44
Danke für den Hinweis
