### ISSUE TITLE
How about the new PHP 7

### ISSUE THREAD

**Issue by halojoy** [flatCore/flatCore-CMS#26]
Anybody knows or has tested FlatCore with PHP 7?
I think it is not difficult to get it running on PHP 7.

**Comment by Webmeteor** [comment]
Flatcore sollte auch unter PHP7 funktionieren. Es ist mir zumindest 
nicht bekannt, dass irgendwelche Funktionen genutzt werden, die es in 
PHP7 nicht mehr gibt.




---
Diese E-Mail wurde von Avast Antivirus-Software auf Viren geprüft.
https://www.avast.com/antivirus

**Comment by patkon** [comment]
I've tested flatCore with PHP 7.0.12 and at first sight everything looks good. I will test further versions soon.

**Comment by patkon** [comment]
I have done extensive tests and do not see any problems with PHP7.x
