### ISSUE TITLE
Stored Cross Site Scripting at Group Creation

### ISSUE THREAD

**Issue by kondurujashwanth** [flatCore/flatCore-CMS#31]
**Vulnerability :** Stored XSS
**Severity :** High
**Parameter :** group_name

**Steps to reproduce :** 

1. Go to Dashboard -> Left navigation menu -> Under "User" drop down select "Edit Usergroup" button.
2. Place a payload "><svg onload=alert(1)> in the group_name parameter "group name"
3. Fill the required fields, add users and click on Save button
4. Navigate to "Show all user", Choose the users which you are added to group  and click on "Edit"
5. It can be observed that XSS payload is executed on the application
6. Logout the application and login with valid user credentials
7. Go to "Show all user" , Click on users tab you will see Stored XSS payload is executed on the                application

**What is the Impact ?**

This vulnerability allows an attacker to either permanently or temporarily inject client-side code into the target website. This code executes when the page is loaded by the victim and the client-side code may carry out activities such as: stealing cookies/sessions, modifying the page contents, logging key strokes, etc.

**How to Fix ?**

Sanitize the data collected from input fields before further processing

**Proof :** https://www.youtube.com/watch?v=sNHJAlep3cM&feature=youtu.be

Regards,
Jashwanth

**Comment by patkon** [comment]
I've fixed this issue (input field group_name). But I don't understand the background really: If you have access to the backend anyway, you can access all the data and manipulate or delete them in the worst case.

In any case, I probably still have to check all the input fields within the backend.

Thank you for checking
Patrick

**Comment by nagarajurepala** [comment]
Thanks for Quick Fix !

**Comment by kondurujashwanth** [comment]
Thanks
