### ISSUE TITLE
Comments page - wrong link

### ISSUE THREAD

**Issue by maulwuff** [flatCore/flatCore-CMS#33]
the link icon for comment on "ungeordnete Seiten" leads to 
`The requested URL /acp/core/ajax.comments.php was not found on this server.`
because it is missing the subfolder like http://example.com/myFlatCoreInstall/acp/....

If you put it to the left side "geordnete Seiten" you get `The requested content cannot be loaded.`

Tested on 1.4.7 B: 76

**Comment by patkon** [comment]
Thank you for reporting, I've fixed that.
