### ISSUE TITLE
English with the dashboard

### ISSUE THREAD

**Issue by pointtom** [flatCore/flatCore-CMS#36]
Have installed flatCore and have changed the $languagePack = "en";
But the admin area is in German or Dutch.
How do I fix this.
Tom

**Comment by patkon** [comment]
You can switch to EN by the Link "Sprache" in the Dashboard.
I admit, this is not very user friendly. I will replace this with country flags.
![bildschirmfoto 2017-08-15 um 08 53 18](https://user-images.githubusercontent.com/5982156/29305191-93bcbd7c-8197-11e7-84ae-4e729faeaad2.png)

**Comment by pointtom** [comment]
Works, thank you.On Aug 15, 2017 4:56 PM, Patrick <notifications@github.com> wrote:You can switch to EN by the Link "Sprache" in the Dashboard.
I admit, this is not very user friendly. I will replace this with country flags.

**Comment by pointtom** [comment]
Check out editor as well. In Dutch.On Aug 15, 2017 6:05 PM, Tom Duncan <tom@ctd.noip.me> wrote:Works, thank you.On Aug 15, 2017 4:56 PM, Patrick <notifications@github.com> wrote:You can switch to EN by the Link "Sprache" in the Dashboard.
I admit, this is not very user friendly. I will replace this with country flags.
