### ISSUE TITLE
There is an arbitrary file upload vulnerability

### ISSUE THREAD

**Issue by geeeez** [flatCore/flatCore-CMS#38]
There are any files uploaded in the background of your website, you can upload PHP files, so that if the administrator password is leaked, the file uploaded through here can be directly getshell, take over the web
example: 
![image](https://user-images.githubusercontent.com/29922543/55206040-1d894300-5210-11e9-851b-37d846ebff42.png)

![image](https://user-images.githubusercontent.com/29922543/55206005-034f6500-5210-11e9-9f48-3b8e5b0b0dad.png)
I think you should limit the type of file you upload

**Comment by patkon** [comment]
I'll look for a solution.
But to install addons you have to be able to upload PHP files. That is a dilemma.

**Comment by patkon** [comment]
uploads (file types) are now limited by the config.php file
https://github.com/flatCore/flatCore-CMS/commit/0c445d045f66649e7c1572b250ebdb8b9e210ee8
