### ISSUE TITLE
Pagemanager

### ISSUE THREAD

**Issue by gtbu** [flatCore/flatCore-CMS#41]
What Your CMS is still missing is a pagemanager with treeview, which gives very much better overview (exists as plugin for wordpress, typesetter and cmsimple etc.)

**Comment by patkon** [comment]
Good point

**Comment by patkon** [comment]
I have add a treeview to the editor. It is a beginning. Of course, it would be really nice to move the pages using drag & drop.
![screenshot-acp-pages-order](https://user-images.githubusercontent.com/5982156/109057769-7571a280-76e2-11eb-8806-724291c0f76b.jpg)

**Comment by patkon** [comment]
Here's a new solutions: https://github.com/flatCore/bulkedit.mod
