### ISSUE TITLE
Stored XSS in Index

### ISSUE THREAD

**Issue by ngochieu-kiminawa** [flatCore/flatCore-CMS#57]
**Describe the bug**
Cross Site Scripting (XSS) via save Exclude URLs

**To Reproduce**
1. Login to flatcore CMS
2. Click on 'Create new Page' after click 'Index'
3. Insert into a XSS payload in Exclude URLs
4. And XSS save on : http://domain/acp/acp.php?tn=pages&sub=index
**Screenshots**
![image](https://user-images.githubusercontent.com/57703587/132238423-51e4bfd2-ecf0-44cd-a6f7-a7ef667c82b0.png)
XSS payload 
<script>alert(1)</script>

**Desktop (please complete the following information):**
 - OS: all
 - Browser : all
 - Version : all

**Additional context**
The XSS attack will help the hacker get the login session of other users requiring them to have at least one "Create new Pages" permission.

**Comment by ngochieu-kiminawa** [comment]
@patkon

**Comment by patkon** [comment]
I'll fix that as soon as possible.
