### ISSUE TITLE
Server-side request forgery vulnerability (SSRF)

### ISSUE THREAD

**Issue by Reclu3a** [flatCore/flatCore-CMS#60]
**Describe the bug**
Server-side request forgery vulnerability (SSRF)

**To Reproduce**
1.go to 'acp/acp.php?tn=pages&sub=index'
2. Enter the intranet address in the box to request
3. Can make a request to the intranet

**Screenshots**
![image](https://user-images.githubusercontent.com/20243850/133184785-4c052298-6c42-45b4-a5b7-6d7f1b44c295.png)

request packet

![image](https://user-images.githubusercontent.com/20243850/133186670-23d46f56-edeb-4161-9b53-be9a8dd53fe6.png)

Locate the vulnerable code  `/acp/core/pages.index.php`
The start_index parameter calls the function fc_crawler

![image](https://user-images.githubusercontent.com/20243850/133186803-e00dfdc5-80c0-4a6b-9e4c-41e37bb7fa45.png)

Tracing the fc_crawler function
Locate the vulnerable code `/acp/core/functions_index.php`

![image](https://user-images.githubusercontent.com/20243850/133187130-8fcede95-b874-4ada-9a5b-e64f88660ea0.png)

Continue to track the fc_loadSourceCode function

![image](https://user-images.githubusercontent.com/20243850/133187241-77f3941f-c481-46e5-bb97-cc5e2a53f20d.png)

![image](https://user-images.githubusercontent.com/20243850/133189297-647836e1-8b82-46a8-aae4-16ef8ea552f3.png)

dict protocol for request 
```
dict://ip:port
```
![image](https://user-images.githubusercontent.com/20243850/133189477-4e48383a-35c2-4af7-97a8-a48d8644feab.png)

Use gopher protocol for request
`gopher://192.168.172.114:9333/aaaaa`
![image](https://user-images.githubusercontent.com/20243850/133190779-5cb300e2-d3be-4e38-b6a9-72e1c597f9f7.png)

Led to the SSRF vulnerability

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser all
 - Version last version

**Comment by patkon** [comment]
I'm a little at a loss about this problem. I hope checking the starting point fixes the problem?

**Comment by LikNK** [comment]
Sorry, I haven’t seen it these days, you can fix it like this
The port for restricting requests can only be port 80, and only HTTP and HTTPS requests are allowed.
Restrict the intellectual property that cannot access the intranet to prevent attacks on the intranet.
Prohibit 302, 301 jump
