### ISSUE TITLE
Permission Missing

### ISSUE THREAD

**Issue by hieuminhnv** [flatCore/flatCore-CMS#65]
**Describe the bug**
Permission Missing  (**bug**/**feature**)...

**To Reproduce**
1. Go to login CMS
2. Click on User >> create user with do not actions (user1 ID=13)
**Screenshots**
![image](https://user-images.githubusercontent.com/28292732/136257202-744da7c9-abf7-4c68-b2db-f0653f675b9e.png)

Account admin (administrator ID=12 )
**Screenshots**
![image](https://user-images.githubusercontent.com/28292732/136257558-eea53a19-cee7-4280-9be8-f0fc90dced5b.png)

3. Edit account **user1** >> in **Username** change to administrator >> **Update User**
Can arbitrarily change the login name. when the **Username** is the same as the admin account, the admin (ID = 12) will can't to delete that user (ID = 13), when it matches another account, the duplicate account will be disabled
**Screenshots**
![image](https://user-images.githubusercontent.com/28292732/136258637-66ade162-a5a5-4b20-8636-bf0fbf407b70.png)

**Desktop (please complete the following information):**
 - OS: All
 - Browser: All
 - Version: Last version

**Comment by patkon** [comment]
I think it's okay, that you can't delete your own account. So you don't accidentally do it. You can still do it via the profile page /profile/

**Comment by patkon** [comment]
No, admins can delete all other users, including other admins.
But if you edit your own account, the delete button is not available.
