### ISSUE TITLE
Responsible disclosure policy

### ISSUE THREAD

**Issue by zidingz** [flatCore/flatCore-CMS#70]
Hey there!

I belong to an open source security research community, and a member (@haxatron) has found an issue, but doesn’t know the best way to disclose it.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by Haxatron** [comment]
Hi there, thanks for validating and fixing the vulnerabilities!

Have submitted 2 more reports:

https://huntr.dev/bounties/ee5fba4a-dd6a-4bba-b9dd-d73bcca0f38e/
https://huntr.dev/bounties/c32d57a0-2955-4bd5-80a9-9b5648ec2f28/

Please take your time to review them.
