### ISSUE TITLE
redirected you too many times

### ISSUE THREAD

**Issue by bluesky0341** [flatCore/flatCore-CMS#83]
how are you?

for [Version 2.1.1]
after i have installed,when i open the site,can not open
This page isn’t working
redirected you too many times.
ERR_TOO_MANY_REDIRECTS

for [Version 2.1.0],it is ok.

**Comment by patkon** [comment]
Hmh, here are a few ideas you can try
- Delete the Template-Cache (ACP -> Dashboard -> Delete Cache)
- open the Page in ACP and save it again
- Start the Update again

Do you use the standard theme or do you have your own?

**Comment by bluesky0341** [comment]
i am sorry that it also can not open
i have deleted cache

**Comment by patkon** [comment]
Maybe something is missing in the database. Navigate in the browser to the /install/ directory.

**Comment by bluesky0341** [comment]
i can open below address
https://siliconnitrideceramic.net/acp/index.php


but i can not open website



in system,
   CMS Domain 

http://siliconnitrideceramic.net


   SSL Domain


   Base URI&nbsp;
/



 
 
 







------------------ 原始邮件 ------------------
发件人:                                                                                                                        "flatCore/flatCore-CMS"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月19日(星期四) 晚上6:41
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [flatCore/flatCore-CMS] redirected you too many times (Issue #83)





 
Maybe something is missing in the database. Navigate in the browser to the /install/ directory.

**Comment by patkon** [comment]
Okay, I think it's a Problem with the Preferences. You can Update from the Develop Branch (I've tested it at the moment). I will merge this Branch in the next days anyway.
Go to  ACP -> System -> Update and klick Update from "Develop Branch". After the Installation is done, navigate to the /install/ Directory.

**Comment by bluesky0341** [comment]
i have also installed the site into two different web hosting,all is not ok
but Version 2.1.0 is ok

**Comment by bluesky0341** [comment]
i have updated according to above
flatCore Installation & Setup
UPDATE
450 Columns are ready
New Table: fc_options in Database content
New Table: fc_orders in Database content
New Table: fc_themes in Database content
New Column: post_product_shipping_mode in table fc_posts
New Column: post_product_shipping_cat in table fc_posts

also can not open site

**Comment by patkon** [comment]
I think there is a problem with the Preferences (choosing the default theme). You can try to open your Portal Page in the ACP and choose "layout_portal.tpl"
![Bildschirmfoto 2022-05-20 um 08 37 37](https://user-images.githubusercontent.com/5982156/169470222-5be1b0f8-9989-4739-8a65-828f2b8f2a70.png)

**Comment by bluesky0341** [comment]
i have entered ACP admin
when i open preferences,can not find below content





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "flatCore/flatCore-CMS"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月20日(星期五) 下午2:52
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [flatCore/flatCore-CMS] redirected you too many times (Issue #83)





 
I think there is a problem with the Preferences (choosing the default theme). You can try to open your Portal Page in the ACP and choose "layout_portal.tpl"

**Comment by bluesky0341** [comment]
i have changed theme
also can not open


if you want,you can access


https://siliconnitrideceramic.net/acp/index.php
admin88
3%NPR9888






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "flatCore/flatCore-CMS"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月20日(星期五) 下午2:52
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [flatCore/flatCore-CMS] redirected you too many times (Issue #83)





 
I think there is a problem with the Preferences (choosing the default theme). You can try to open your Portal Page in the ACP and choose "layout_portal.tpl"

**Comment by patkon** [comment]
I've deleted your last Comment with the Login Data.

**Comment by patkon** [comment]
I have found the Problem. The "default Language" in ACP -> Language was set to English. And if you have no matching Pages, it will end up with this error. Your Portal Page was set to "German".

I will fix this in the future.

**Comment by bluesky0341** [comment]
thanks
i have not change the portal page setting


after installed
i enter admin


first i can see the language for admin is german
so i choose english in the bottom of admin
you can find photo in the attachment





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "flatCore/flatCore-CMS"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月20日(星期五) 下午3:31
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [flatCore/flatCore-CMS] redirected you too many times (Issue #83)





 
I have found the Problem. The "default Language" in ACP -&gt; Language was set to English. And if you have no matching Pages, it will end up with this error. Your Portal Page was set to "German".
 
I will fix this in the future.

**Comment by patkon** [comment]
This is a bug in the installer. My fault. The default Language is set to english, no matter which language you choose at the installation. I will fix that.

**Comment by bluesky0341** [comment]
the ACP is slow
how should we do?





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "flatCore/flatCore-CMS"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月20日(星期五) 晚上10:37
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [flatCore/flatCore-CMS] redirected you too many times (Issue #83)





 
This is a bug in the installer. My fault. The default Language is set to english, no matter which language you choose at the installation. I will fix that.

**Comment by bluesky0341** [comment]
lauguage is english in ACP


when i entered ACP,sometimes it will be changed into German


also this cms can not support php8.0,this is important





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "flatCore/flatCore-CMS"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月20日(星期五) 晚上10:37
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [flatCore/flatCore-CMS] redirected you too many times (Issue #83)





 
This is a bug in the installer. My fault. The default Language is set to english, no matter which language you choose at the installation. I will fix that.

**Comment by patkon** [comment]
PHP 8 will come with the next major release: https://github.com/flatCore/flatCore-CMS/discussions/82

**Comment by bluesky0341** [comment]
how are you?
when will you release?





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "flatCore/flatCore-CMS"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月21日(星期六) 下午4:58
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [flatCore/flatCore-CMS] redirected you too many times (Issue #83)





 
PHP 8 will come with the next major release: #82

**Comment by patkon** [comment]
It depends on how much time I can spend on the project. The goal is June. But it's ready when it's ready.

**Comment by bluesky0341** [comment]
thanks for reply
why the categories can not be displayed on homepage





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "flatCore/flatCore-CMS"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月21日(星期六) 下午5:07
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [flatCore/flatCore-CMS] redirected you too many times (Issue #83)





 
It depends on how much time I can spend on the project. The goal is June. But it's ready when it's ready.

**Comment by bluesky0341** [comment]
when i write a post in category,i can not find this post from my website




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "flatCore/flatCore-CMS"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月21日(星期六) 下午5:07
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [flatCore/flatCore-CMS] redirected you too many times (Issue #83)





 
It depends on how much time I can spend on the project. The goal is June. But it's ready when it's ready.
