### ISSUE TITLE
How to add or find Modules?

### ISSUE THREAD

**Issue by dosimotion** [flatCore/flatCore-CMS#9]
In der Dokumentation ist nicht beschrieben, wo man Module findet und wie sie installiert werden.

**Comment by patkon** [comment]
Das stimmt, die Dokumentation hängt schwer hinterher. Ich werde das nachholen.
Im Moment stehen nur diese Module zur Verfügung: https://github.com/flatCore
Die Installation ist relativ einfach:

1. Modul laden, z.B.: https://github.com/flatCore/siteLock/archive/master.zipModul runterladen.

**Comment by dosimotion** [comment]
Und wie installiere ich es? Muss ich es in ein bestimmtes Verzeichnis legen?

Am 21.09.2016 17:24 schrieb "Patrick" <notifications@github.com>:

**Comment by patkon** [comment]
Ja, in den Ordner [/modules/](https://github.com/flatCore/flatCore-CMS/tree/master/modules)
